name: "ğŸš€ release"

on:
    push:
        branches:
          - master

jobs:
    release:
        name: ğŸš€ Public npm
        runs-on: ubuntu-latest
        steps:
            - name: ğŸ“š checkout
              uses: actions/checkout@v2.1.1
            - name: ğŸ’¥ node
              uses: actions/setup-node@v2
              with:
                  node-version: 14
                  registry-url: https://registry.npmjs.org
            - name: ğŸ”§ Install dependencies and build
              run: npm ci
            - name: ğŸš€ publish new version
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}